language: cpp
compiler: gcc
os: 
    - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.x
    packages:
      - cmake
      - cmake-data
      - gcc-7
      - g++-7
      - libglu1-mesa-dev
      - xorg-dev
      - libasound2-dev
env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
script:
    - git --version
    # setup and check fips
    - git clone https://github.com/floooh/fips.git ../fips
    # build
    - python fips list targets
    - python fips gen
    - python fips build
    # run tests
    - python fips run crTest
